#!/bin/bash

: ${PREFIX:=vulcand}
if [[ ! -z "$CONFD" ]]; then
	confd -confdir="/tpl.confd" -interval=5 -prefix="/$PREFIX/"
elif [[ ! -z "$CONSUL" ]]; then
	confd -backend consul -node $CONSUL -confdir="/tpl.confd" -interval=5 -prefix="/$PREFIX/"
else
  sleep 999
fi
