[template]
src   = "nginx.conf"
dest  = "/etc/nginx/nginx.conf"
uid = 0
gid = 0
mode  = "0644"
keys = [
  "/backends",
  "/frontends",
  "/cert"
]
check_cmd = "/usr/bin/python3 /certctl.py open_keypair -sealKey ${SEALKEY} -dir /etc/nginx/ssl && /usr/sbin/nginx -t -c {{.src}}"
reload_cmd = "/usr/sbin/nginx -s reload"